#!/usr/bin/env zsh
set -euo pipefail

# ============================================================
# AskUserQuestion Duplicate Bug — Investigation Harness
# Generated by overnight-harness-builder (Investigation Mode)
# ============================================================

# --- Configuration ---
TASK_NAME="AskUserQuestion Duplicate Bug"
MAX_ROUNDS=4        # 4 hypotheses → 4 rounds max
INVESTIGATOR_TOOLS="Read,Grep,Glob,Bash"

# --- Directories ---
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
EVIDENCE_DIR="${HARNESS_DIR}/evidence"
PROMPTS_DIR="${HARNESS_DIR}/prompts"
PROGRESS_FILE="${HARNESS_DIR}/progress.md"
SPEC_FILE="${HARNESS_DIR}/SPEC.md"
ROOT_CAUSE_FILE="${HARNESS_DIR}/root-cause-report.md"

# --- Flags ---
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

mkdir -p "$EVIDENCE_DIR"

# --- Functions ---

get_hypothesis_status() {
  local confirmed=$(grep -c "CONFIRMED" "$PROGRESS_FILE" 2>/dev/null || echo "0")
  local eliminated=$(grep -c "ELIMINATED" "$PROGRESS_FILE" 2>/dev/null || echo "0")
  local inconclusive=$(grep -c "INCONCLUSIVE" "$PROGRESS_FILE" 2>/dev/null || echo "0")
  echo "confirmed=${confirmed} eliminated=${eliminated} inconclusive=${inconclusive}"
}

append_progress() {
  local round=$1 hypothesis=$2 status=$3 summary=$4
  local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
  echo "| ${round} | ${timestamp} | ${hypothesis} | ${status} | ${summary} |" >> "$PROGRESS_FILE"
}

run_investigator() {
  local round=$1
  local prompt=$(cat "$PROMPTS_DIR/investigator.md")

  # Inject round-specific context
  prompt="${prompt}

---
## Round Context (injected by orchestrator)

This is investigation round ${round} of ${MAX_ROUNDS}.

**Instructions:**
1. Read SPEC.md at: ${SPEC_FILE}
2. Read progress.md at: ${PROGRESS_FILE}
3. Read all files in evidence/ at: ${EVIDENCE_DIR}/
4. Select the next unverified hypothesis and investigate it
5. Write your findings to: ${EVIDENCE_DIR}/h{N}-{hypothesis-name}.md"

  echo "Invoking claude -p with Investigator prompt (round ${round})..."
  claude -p "$prompt" --allowedTools "$INVESTIGATOR_TOOLS" 2>&1 || {
    echo "ERROR: Investigator failed on round ${round}" >&2
    return 1
  }
}

# --- Main Loop ---

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ${TASK_NAME} — Investigation Harness                   ║"
echo "║  Max rounds: ${MAX_ROUNDS}                              ║"
echo "║  Hypotheses: H1(CLI auto-accept) H2(LLM triple-call)   ║"
echo "║              H3(Skill prompt gap) H4(Frontend dedup)    ║"
echo "╚══════════════════════════════════════════════════════════╝"

if $DRY_RUN; then
  echo ""
  echo "[DRY RUN] Would run up to ${MAX_ROUNDS} investigation rounds"
  echo ""
  echo "Hypotheses from SPEC.md:"
  grep -E "^### H[0-9]" "$SPEC_FILE" 2>/dev/null || echo "(none found)"
  echo ""
  echo "Evidence directory: ${EVIDENCE_DIR}/"
  echo "Progress file: ${PROGRESS_FILE}"
  echo ""
  echo "Investigator tools: ${INVESTIGATOR_TOOLS}"
  echo ""
  echo "Exit conditions:"
  echo "  - Root cause CONFIRMED (any hypothesis)"
  echo "  - All hypotheses ELIMINATED (dead end)"
  echo "  - Max rounds reached (${MAX_ROUNDS})"
  exit 0
fi

for i in $(seq 1 $MAX_ROUNDS); do
  echo ""
  echo "━━━ Investigation Round $i / $MAX_ROUNDS ━━━"

  # Check if root cause already confirmed (from previous round)
  if ls "$EVIDENCE_DIR"/*.md 1>/dev/null 2>&1; then
    if grep -ql "CONFIRMED" "$EVIDENCE_DIR"/*.md 2>/dev/null; then
      echo "Root cause already CONFIRMED in a previous round. Skipping."
      break
    fi
  fi

  # Run Investigator
  echo "[Step 1] Running Investigator..."
  run_investigator $i || {
    echo "Investigator failed. Stopping."
    append_progress "$i" "N/A" "ERROR" "Investigator failure"
    break
  }

  # Git snapshot
  git add -A && git commit -m "investigate: round ${i}" --allow-empty 2>/dev/null || true

  # Check for new evidence files
  latest_evidence=$(ls -t "$EVIDENCE_DIR"/*.md 2>/dev/null | head -1)
  if [[ -n "$latest_evidence" ]]; then
    # Extract hypothesis name and status from evidence file
    hypothesis=$(basename "$latest_evidence" .md)

    # Try both Chinese and English judgment formats
    status=$(grep -oP '(Judgment|判断)[：:]\s*\K\w+' "$latest_evidence" 2>/dev/null | head -1 || echo "UNKNOWN")
    summary=$(grep -A1 -E "(Rationale|理由)" "$latest_evidence" 2>/dev/null | tail -1 | cut -c1-80 || echo "N/A")

    append_progress "$i" "$hypothesis" "$status" "$summary"
    echo "   Hypothesis: ${hypothesis}"
    echo "   Status: ${status}"
  else
    append_progress "$i" "N/A" "NO_OUTPUT" "No evidence file produced"
    echo "   WARNING: No evidence file produced"
  fi

  # Exit condition 1: Root cause found
  if ls "$EVIDENCE_DIR"/*.md 1>/dev/null 2>&1; then
    if grep -ql "CONFIRMED" "$EVIDENCE_DIR"/*.md 2>/dev/null; then
      echo ""
      echo "Root cause CONFIRMED! Generating root cause report..."

      confirmed_files=$(grep -rl "CONFIRMED" "$EVIDENCE_DIR"/*.md 2>/dev/null)
      {
        echo "# Root Cause Report"
        echo ""
        echo "## Bug: AskUserQuestion Duplicate Rendering & Auto-Answer"
        echo ""
        echo "## Confirmed Root Cause(s)"
        echo ""
        for f in $confirmed_files; do
          echo "### $(basename "$f" .md)"
          echo ""
          cat "$f"
          echo ""
          echo "---"
          echo ""
        done
        echo "## Investigation Summary"
        echo ""
        cat "$PROGRESS_FILE"
      } > "$ROOT_CAUSE_FILE"

      git add -A && git commit -m "investigate: root cause confirmed (round ${i})" 2>/dev/null || true
      break
    fi
  fi

  # Exit condition 2: All hypotheses eliminated
  total_hypotheses=$(grep -cE "^### H[0-9]" "$SPEC_FILE" 2>/dev/null || echo "0")
  eliminated=0
  if ls "$EVIDENCE_DIR"/*.md 1>/dev/null 2>&1; then
    eliminated=$(grep -cl "ELIMINATED" "$EVIDENCE_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ')
  fi
  if [[ "$eliminated" -ge "$total_hypotheses" && "$total_hypotheses" -gt 0 ]]; then
    echo ""
    echo "All ${total_hypotheses} hypotheses ELIMINATED. Dead end reached."
    echo "Check evidence/ for details. Consider generating new hypotheses."
    append_progress "$i" "ALL" "DEAD_END" "All hypotheses eliminated — need new hypotheses or human review"
    break
  fi
done

echo ""
echo "━━━ Investigation Complete ━━━"
echo "Progress: ${PROGRESS_FILE}"
echo "Evidence: ${EVIDENCE_DIR}/"
if [[ -f "$ROOT_CAUSE_FILE" ]]; then
  echo "Root cause report: ${ROOT_CAUSE_FILE}"
else
  echo "No root cause confirmed yet."
fi
echo "History: git log --grep='investigate:' --oneline"
