#!/usr/bin/env bash
set -eu

# ============================================================
# entity-document-promotion Harness — Code Mode Iteration Loop
# Generated by overnight-harness-builder
#
# Promotes @kedge-agentic/entity-document to CCAAS component:
#   TransformRegistry + block-utils + DocumentEditProvider
# ============================================================

# --- Nested Session Guard ---
# Required when harness is launched from inside a Claude Code session.
# env -u is more reliable than unset in sandboxed environments.
claude_safe() {
  env -u CLAUDECODE \
      -u CLAUDE_CODE_ENTRYPOINT \
      -u CLAUDE_CODE_DISABLE_TERMINAL_TITLE \
      -u CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS \
      claude "$@"
}

# --- Configuration ---
TASK_NAME="entity-document-promotion"
MAX_ITERATIONS=8
SCORE_THRESHOLD=90
MIN_IMPROVEMENT=3
ROLLBACK_THRESHOLD=5
MAX_COST_USD="${MAX_COST:-150}"

# Agent tool permissions
GENERATOR_TOOLS="Read,Write,Edit,Grep,Glob,Bash"
EVALUATOR_TOOLS="Read,Grep,Glob,Bash"

# Cost estimates
COST_PER_ITERATION=5.00

# --- Directories ---
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
EVAL_DIR="${HARNESS_DIR}/eval-reports"
CHANGELOG_DIR="${HARNESS_DIR}/changelogs"
PROMPTS_DIR="${HARNESS_DIR}/prompts"
PROGRESS_FILE="${HARNESS_DIR}/progress.md"

# Frozen files (MUST NOT be modified)
FROZEN_FILES="packages/entity-document/src/__tests__/transforms.test.ts
packages/entity-document/src/__tests__/round-trip.test.ts
packages/entity-document/src/__tests__/str-replace.test.ts
packages/entity-document/src/__tests__/cross-block.test.ts
packages/context-layer/src/core/interfaces.ts
packages/context-layer/src/core/context-router.ts
packages/context-layer/src/core/entity-registry.ts"

# --- Flags ---
DRY_RUN=false
RESUME=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --resume) RESUME=true ;;
    --max-cost=*) MAX_COST_USD="${arg#*=}" ;;
  esac
done

# --- Functions ---

get_last_version() {
  local last=$(ls "${EVAL_DIR}"/v*-eval.md 2>/dev/null | sort -V | tail -1)
  if [[ -n "$last" ]]; then
    basename "$last" | sed 's/[^0-9]//g'
  else
    echo "0"
  fi
}

extract_score() {
  local eval_file="$1"
  grep -E '(总分|Total)[：:][[:space:]]*[0-9]+' "$eval_file" | head -1 | sed 's/.*[：:][[:space:]]*//' | sed 's|/.*||' | tr -d '[:space:]'
}

estimate_cost() {
  local iterations=$1
  echo "scale=2; $iterations * $COST_PER_ITERATION" | bc
}

append_progress() {
  local version=$1 score=$2 changes=$3 top_issue=$4
  local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
  echo "| v${version} | ${timestamp} | ${score}/100 | ${changes} | ${top_issue} |" >> "$PROGRESS_FILE"
}

check_frozen_files() {
  local violations=0
  cd "$REPO_ROOT"
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    if git diff --name-only | grep -qF "$f"; then
      echo "FROZEN FILE VIOLATION: $f was modified. Reverting."
      git checkout -- "$f"
      violations=$((violations + 1))
    fi
  done <<< "$FROZEN_FILES"
  return $violations
}

run_validation() {
  echo "  [Validation] Running typecheck + tests..."
  local errors=0

  cd "${REPO_ROOT}/packages/entity-document"
  if ! npx vitest run 2>&1 | tail -5; then
    echo "  [Validation] entity-document vitest FAILED"
    errors=$((errors + 1))
  fi

  if ! npx tsc --noEmit 2>&1 | tail -3; then
    echo "  [Validation] entity-document tsc FAILED"
    errors=$((errors + 1))
  fi

  cd "${REPO_ROOT}/packages/context-layer"
  if ! npx tsc --noEmit 2>&1 | tail -3; then
    echo "  [Validation] context-layer tsc FAILED"
    errors=$((errors + 1))
  fi

  cd "${REPO_ROOT}/solutions/business/edu-platform/backend"
  if ! npx tsc --noEmit 2>&1 | tail -3; then
    echo "  [Validation] edu-platform backend tsc FAILED"
    errors=$((errors + 1))
  fi

  # @nestjs leak check
  cd "$REPO_ROOT"
  if grep -r "from '@nestjs" packages/entity-document/src/ 2>/dev/null | grep -v node_modules | grep -q .; then
    echo "  [Validation] @nestjs LEAK in entity-document!"
    errors=$((errors + 1))
  fi

  cd "$REPO_ROOT"
  return $errors
}

run_generator() {
  local version=$1
  local prev=$((version - 1))
  local prompt=$(cat "$PROMPTS_DIR/generator.md")

  # Inject iteration-specific context
  if [[ $version -eq 1 ]]; then
    prompt="${prompt}

---
## 迭代上下文（编排器注入）

这是**第一轮**迭代 (v1)。从头实现所有 Phase。

**你的起点**：先读 SPEC.md 和现有源码，然后按 Phase 1→2→3→4 顺序创建新文件并修改现有文件。

**优先级**：Phase 1 (TransformRegistry) + Phase 2 (block-utils) 最关键。如果时间不够，先确保这两个 Phase 完成。

**Changelog 保存到**: ${CHANGELOG_DIR}/v1-changelog.md"
  else
    prompt="${prompt}

---
## 迭代上下文（编排器注入）

这是第 **v${version}** 轮迭代。

**你的起点**：源码已被前几轮修改。先读现有代码，在此基础上改进。

**读 eval report**: harness-workspace/entity-document-promotion/eval-reports/v${prev}-eval.md — 告诉你哪里扣分了、如何修复。

**策略**：优先修复 eval report 中的 Top Priority Fixes。不要重做已经满分的维度。

**Changelog 保存到**: ${CHANGELOG_DIR}/v${version}-changelog.md"
  fi

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$GENERATOR_TOOLS" 2>&1 || {
    echo "ERROR: Generator failed on v${version}" >&2
    return 1
  }
}

run_evaluator() {
  local version=$1
  local prompt=$(cat "$PROMPTS_DIR/evaluator.md")

  # Inject version number
  prompt=$(echo "$prompt" | sed "s/{N}/${version}/g")

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$EVALUATOR_TOOLS" 2>&1 || {
    echo "ERROR: Evaluator failed on v${version}" >&2
    return 1
  }
}

# --- Pre-flight ---

mkdir -p "$EVAL_DIR" "$CHANGELOG_DIR"

# --- Main Loop ---

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ${TASK_NAME} Harness — Code Mode                          ║"
echo "║  Artifacts:                                                 ║"
echo "║    packages/entity-document/src/                            ║"
echo "║    packages/context-layer/src/core/                         ║"
echo "║    solutions/.../referenceable/                             ║"
echo "║  Max iterations: ${MAX_ITERATIONS}  |  Threshold: ${SCORE_THRESHOLD}/100              ║"
echo "║  Cost cap: \$${MAX_COST_USD}                                            ║"
echo "╚══════════════════════════════════════════════════════════════╝"

if $RESUME; then
  START_VERSION=$(( $(get_last_version) + 1 ))
  echo "Resuming from v${START_VERSION}..."
else
  START_VERSION=1
fi

if $DRY_RUN; then
  remaining=$((MAX_ITERATIONS - START_VERSION + 1))
  est=$(estimate_cost $remaining)
  echo "[DRY RUN] Would run ${remaining} iterations, estimated cost: \$${est}"
  exit 0
fi

low_improvement_count=0
prev_score=0

# If resuming, recover prev_score from last eval
if [[ $START_VERSION -gt 1 ]]; then
  prev_eval="${EVAL_DIR}/v$((START_VERSION - 1))-eval.md"
  if [[ -f "$prev_eval" ]]; then
    prev_score=$(extract_score "$prev_eval" || echo "0")
  fi
fi

for i in $(seq $START_VERSION $MAX_ITERATIONS); do
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Iteration $i / $MAX_ITERATIONS"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Cost check
  completed=$((i - START_VERSION))
  spent=$(estimate_cost $completed)
  if (( $(echo "$spent > $MAX_COST_USD" | bc -l) )); then
    echo "Cost cap reached (\$${spent} > \$${MAX_COST_USD}). Stopping."
    break
  fi

  # ─── Step 1: Generator ───
  echo ""
  echo "  [Step 1/5] Running Generator..."
  run_generator $i || {
    echo "  Generator failed. Retrying once..."
    sleep 5
    run_generator $i || {
      echo "  Generator failed twice. Stopping."
      append_progress $i "ERROR" "Generator failure" "N/A"
      break
    }
  }

  # ─── Step 2: Frozen file check ───
  echo ""
  echo "  [Step 2/5] Checking frozen files..."
  cd "$REPO_ROOT"
  check_frozen_files
  frozen_violations=$?
  if [[ $frozen_violations -gt 0 ]]; then
    echo "  WARNING: ${frozen_violations} frozen file(s) reverted."
  fi

  # ─── Step 3: Validation (typecheck + tests) ───
  echo ""
  echo "  [Step 3/5] Running validation..."
  if ! run_validation; then
    echo "  Validation had failures — evaluator will score accordingly."
    echo "  (Not reverting: eval feedback needed to fix issues)"
  fi

  # ─── Git snapshot: Generator iteration ───
  cd "$REPO_ROOT"
  git add \
    packages/entity-document/ \
    packages/context-layer/src/core/ \
    packages/context-layer/package.json \
    solutions/business/edu-platform/backend/src/referenceable/ \
    "${CHANGELOG_DIR}/" 2>/dev/null || true
  git commit -m "feat(entity-document): promotion v${i} iteration" --allow-empty 2>/dev/null || true

  # ─── Step 4: Evaluator ───
  echo ""
  echo "  [Step 4/5] Running Evaluator..."
  run_evaluator $i || {
    echo "  Evaluator failed. Retrying once..."
    sleep 5
    run_evaluator $i || {
      echo "  Evaluator failed twice. Stopping."
      append_progress $i "ERROR" "Evaluator failure" "N/A"
      break
    }
  }

  # ─── Step 5: Extract results from FILES ───
  echo ""
  echo "  [Step 5/5] Extracting results..."

  eval_file="${EVAL_DIR}/v${i}-eval.md"
  if [[ ! -f "$eval_file" ]]; then
    echo "  Eval report not found at ${eval_file}. Stopping."
    append_progress $i "ERROR" "No eval report" "N/A"
    break
  fi

  score=$(extract_score "$eval_file")
  if [[ -z "$score" ]]; then
    echo "  Could not extract score from eval report. Stopping."
    append_progress $i "ERROR" "Score extraction failed" "N/A"
    break
  fi

  # Extract key changes from changelog FILE
  changelog_file="${CHANGELOG_DIR}/v${i}-changelog.md"
  if [[ -f "$changelog_file" ]]; then
    changes=$(grep "^- " "$changelog_file" | head -3 | tr '\n' '; ' | cut -c1-100)
  else
    changes="(no changelog file)"
  fi

  # Extract top issue from eval report FILE
  top_issue=$(grep -A1 "Priority Fix" "$eval_file" 2>/dev/null | tail -1 | sed 's/^[0-9. ]*//' | cut -c1-80 || echo "N/A")

  append_progress "$i" "$score" "$changes" "$top_issue"
  echo "  Score: ${score}/100"

  # Git snapshot: eval
  cd "$REPO_ROOT"
  git add "${EVAL_DIR}/" "${PROGRESS_FILE}" 2>/dev/null || true
  git commit -m "feat(entity-document): promotion v${i} eval — score ${score}/100" --allow-empty 2>/dev/null || true

  # ─── Exit conditions ───

  # 1. Score threshold
  if [[ "$score" -ge "$SCORE_THRESHOLD" ]]; then
    echo ""
    echo "  Score threshold reached! (${score} >= ${SCORE_THRESHOLD})"
    break
  fi

  # 2. Regression detection + auto-revert
  if [[ $prev_score -gt 0 && $score -lt $((prev_score - ROLLBACK_THRESHOLD)) ]]; then
    echo ""
    echo "  REGRESSION detected: ${prev_score} -> ${score} (delta < -${ROLLBACK_THRESHOLD}). Reverting source files."
    cd "$REPO_ROOT"
    git checkout HEAD~2 -- \
      packages/entity-document/src/ \
      packages/context-layer/src/core/document-edit-provider.ts \
      solutions/business/edu-platform/backend/src/referenceable/ 2>/dev/null || true
    git add -A && git commit -m "feat(entity-document): promotion v${i} REVERTED — regression ${prev_score}->${score}" 2>/dev/null || true
    # Don't update prev_score — keep the pre-regression score
    continue
  fi

  # 3. Diminishing returns
  if [[ $prev_score -gt 0 ]]; then
    improvement=$((score - prev_score))
    if [[ $improvement -lt $MIN_IMPROVEMENT ]]; then
      low_improvement_count=$((low_improvement_count + 1))
      if [[ $low_improvement_count -ge 2 ]]; then
        echo ""
        echo "  Diminishing returns (< ${MIN_IMPROVEMENT} points for 2 consecutive iterations). Stopping."
        echo "  Bottleneck: ${top_issue}"
        break
      fi
      echo "  Low improvement (${improvement} pts). Count: ${low_improvement_count}/2"
    else
      low_improvement_count=0
    fi
  fi

  prev_score=$score
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Run Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Progress:  ${PROGRESS_FILE}"
echo "  Source:    packages/entity-document/src/"
echo "  Base:      packages/context-layer/src/core/document-edit-provider.ts"
echo "  Adapters:  solutions/.../referenceable/"
echo "  History:   git log --grep='entity-document.*promotion' --oneline"
echo ""
echo "  Next steps:"
echo "    cat ${PROGRESS_FILE}"
echo "    cd packages/entity-document && npx vitest run"
echo "    cd packages/entity-document && npx tsc --noEmit"
