#!/usr/bin/env bash
set -eu

# ============================================================
# Lesson & Template Harness — Frontend 教案管理 + 模板管理
# Generated by overnight-harness-builder (Code Mode)
# ============================================================

# --- Nested Session Guard ---
claude_safe() {
  env -u CLAUDECODE \
      -u CLAUDE_CODE_ENTRYPOINT \
      -u CLAUDE_CODE_DISABLE_TERMINAL_TITLE \
      -u CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS \
      claude "$@"
}

# --- Configuration ---
TASK_NAME="lesson-template"
MAX_ITERATIONS=8
SCORE_THRESHOLD=90
MIN_IMPROVEMENT=3
ROLLBACK_THRESHOLD=5
MAX_COST_USD="${MAX_COST:-100}"

# Agent tool permissions
GENERATOR_TOOLS="Read,Write,Edit,Grep,Glob,Bash"
EVALUATOR_TOOLS="Read,Write,Grep,Glob,Bash"

COST_PER_ITERATION=5.00  # higher estimate: complex BlockEditor scope

# --- Directories ---
REPO_ROOT="$(cd "$(dirname "$0")/../../../../../.." && pwd)"
SOLUTION_DIR="${REPO_ROOT}/solutions/business/edu-platform"
FRONTEND_DIR="${SOLUTION_DIR}/frontend"
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
EVAL_DIR="${HARNESS_DIR}/eval-reports"
CHANGELOG_DIR="${HARNESS_DIR}/changelogs"
PROMPTS_DIR="${HARNESS_DIR}/prompts"
PROGRESS_FILE="${HARNESS_DIR}/progress.md"

# Frozen paths (must NOT be modified by generator)
# Includes Harness B outputs + existing frozen files
FROZEN_PATHS=(
  "solutions/business/edu-platform/frontend/src/components/LoginPage.tsx"
  "solutions/business/edu-platform/frontend/src/widgets/"
  "solutions/business/edu-platform/frontend/src/hooks/useEduAuth.ts"
  "solutions/business/edu-platform/frontend/src/components/layout/Sidebar.tsx"
  "solutions/business/edu-platform/frontend/src/components/layout/TopNav.tsx"
  "solutions/business/edu-platform/frontend/src/pages/HomePage.tsx"
  "solutions/business/edu-platform/frontend/src/components/home/"
  "solutions/business/edu-platform/backend/"
  "solutions/business/edu-platform/mcp-server/"
)

# design-tokens.css is append-only (can add, not delete)
# This is checked separately in frozen file check

# --- Flags ---
DRY_RUN=false
RESUME=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true ;;
    --resume) RESUME=true ;;
    --max-cost) shift; MAX_COST_USD="$1" ;;
    --max-cost=*) MAX_COST_USD="${1#*=}" ;;
  esac
  shift
done

# --- Functions ---

get_last_version() {
  local last=$(ls "${EVAL_DIR}"/v*-eval.md 2>/dev/null | sort -V | tail -1)
  if [[ -n "$last" ]]; then
    basename "$last" | sed 's/[^0-9]//g'
  else
    echo "0"
  fi
}

extract_score() {
  local eval_file="$1"
  local score
  # Primary: find "总分" or "Total" line with "XX/100" (most specific)
  score=$(grep -E '(^##[[:space:]]*)?总分|Total' "$eval_file" | grep -oE '[0-9]+/100' | head -1 | cut -d/ -f1)
  if [[ -n "$score" ]]; then
    echo "$score"
    return
  fi
  # Fallback: first "XX/100" in top 20 lines (avoid stray predictions near EOF)
  score=$(head -20 "$eval_file" | grep -oE '[0-9]+/100' | head -1 | cut -d/ -f1)
  if [[ -n "$score" ]]; then
    echo "$score"
    return
  fi
  # Last resort: any "总分" or "Total" line
  grep -E '(总分|Total)[：:][[:space:]]*[0-9]+' "$eval_file" | head -1 | grep -oE '[0-9]+' | head -1
}

estimate_cost() {
  local iterations=$1
  echo "scale=2; $iterations * $COST_PER_ITERATION" | bc
}

append_progress() {
  local version=$1 score=$2 d1=$3 d2=$4 d3=$5 d4=$6 d5=$7 top_issue=$8
  local timestamp=$(date '+%Y-%m-%d %H:%M')
  echo "| v${version} | ${timestamp} | ${score} | ${d1} | ${d2} | ${d3} | ${d4} | ${d5} | ${top_issue} |" >> "$PROGRESS_FILE"
}

append_progress_simple() {
  local version=$1 score=$2 top_issue=$3
  local timestamp=$(date '+%Y-%m-%d %H:%M')
  echo "| v${version} | ${timestamp} | ${score} | - | - | - | - | - | ${top_issue} |" >> "$PROGRESS_FILE"
}

check_frozen_files() {
  local violations=0
  cd "$REPO_ROOT"
  for frozen_path in "${FROZEN_PATHS[@]}"; do
    local changed
    changed=$(git diff --name-only | grep "^${frozen_path}" 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$changed" -gt 0 ]]; then
      echo "  FROZEN PATH VIOLATION: ${frozen_path} has ${changed} modified file(s). Reverting."
      git diff --name-only | grep "^${frozen_path}" | xargs -I{} git checkout -- "{}"
      violations=$((violations + changed))
    fi
  done

  # Special check: design-tokens.css append-only
  local tokens_file="solutions/business/edu-platform/frontend/src/styles/design-tokens.css"
  if git diff --name-only | grep -q "${tokens_file}" 2>/dev/null; then
    # Check if any lines were removed (only additions allowed)
    local deletions
    deletions=$(git diff "${tokens_file}" | grep '^-[^-]' | wc -l | tr -d ' ')
    if [[ "$deletions" -gt 0 ]]; then
      echo "  FROZEN PATH VIOLATION: design-tokens.css has ${deletions} deleted line(s). Reverting."
      git checkout -- "${tokens_file}"
      violations=$((violations + 1))
    fi
  fi

  return $violations
}

run_validation() {
  echo "  [Validation] Installing dependencies..."
  cd "$FRONTEND_DIR"
  npm install 2>&1 | tail -3

  echo "  [Validation] TypeScript type check..."
  if npx tsc --noEmit 2>&1; then
    echo "  [Validation] TSC PASS"
    return 0
  else
    echo "  [Validation] TSC FAIL — Generator must fix before eval"
    return 1
  fi
}

run_generator() {
  local version=$1
  local prev=$((version - 1))
  local prompt=$(cat "$PROMPTS_DIR/generator.md")

  # Replace {N} and {N-1} placeholders
  prompt="${prompt//\{N-1\}/${prev}}"
  prompt="${prompt//\{N\}/${version}}"

  if [[ $version -eq 1 ]]; then
    prompt="${prompt}

---
## Iteration Context (injected by orchestrator)

This is the **FIRST** iteration (v1). Create all files from scratch.

**Your starting point**: Frontend has TopNav + HomePage + design-tokens.css (from Harness B). The \`/lesson-plans\` and \`/templates\` routes are placeholders. Create:
1. Install \`@dnd-kit/core @dnd-kit/sortable\`
2. Create BlockEditor + 7 block type components in \`components/editor/\`
3. Create 4 page components: LessonPlanList, LessonPlanEditor, TemplateList, TemplateEditor
4. Create RequirementBanner + PromoteModal + BlockTypeSelector
5. Create types/lesson-plan.ts and types/template.ts
6. Update App.tsx with 6 new routes

**Priority**: Get \`npx tsc --noEmit\` to pass first. Then BlockEditor basic rendering. Then pages.

**Save changelog to**: ${CHANGELOG_DIR}/v1-changelog.md"
  else
    prompt="${prompt}

---
## Iteration Context (injected by orchestrator)

This is iteration **v${version}**.

**Your starting point**: Read existing files in \`frontend/src/\` — they have been modified by prior iterations. Continue from here, DO NOT recreate from scratch.

**Read the eval report**: \`harness-workspace/main-page-and-lesson-plan/lesson-template/eval-reports/v${prev}-eval.md\` — it tells you exactly what to fix.

**Save changelog to**: ${CHANGELOG_DIR}/v${version}-changelog.md"
  fi

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$GENERATOR_TOOLS" 2>&1 || {
    echo "ERROR: Generator failed on v${version}" >&2
    return 1
  }
}

run_evaluator() {
  local version=$1
  local prompt=$(cat "$PROMPTS_DIR/evaluator.md")

  # Inject version number
  prompt="${prompt//\{N\}/${version}}"

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$EVALUATOR_TOOLS" 2>&1 || {
    echo "ERROR: Evaluator failed on v${version}" >&2
    return 1
  }
}

extract_dim() {
  local dim="$1" file="$2"
  grep "| ${dim} |" "$file" 2>/dev/null | head -1 | awk -F'|' '{gsub(/[[:space:]]/, "", $4); split($4, a, "/"); print a[1]}'
}

# --- Pre-flight ---

command -v bc >/dev/null 2>&1 || { echo "ERROR: 'bc' is required but not installed."; exit 1; }

mkdir -p "$EVAL_DIR" "$CHANGELOG_DIR"

# --- Main Loop ---

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ${TASK_NAME} Harness — Frontend 教案管理 + 模板管理          ║"
echo "║  Artifact: frontend/src/ (BlockEditor + 4 pages + modals)    ║"
echo "║  Dimensions: D1-D5 (BlockEditor/Visual/CRUD/Interaction/Code)║"
echo "║  Max iterations: ${MAX_ITERATIONS}                            ║"
echo "║  Score threshold: ${SCORE_THRESHOLD}/100                      ║"
echo "║  Cost cap: \$${MAX_COST_USD}                                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"

if $RESUME; then
  START_VERSION=$(( $(get_last_version) + 1 ))
  echo "Resuming from v${START_VERSION}..."
else
  START_VERSION=1
fi

if $DRY_RUN; then
  remaining=$((MAX_ITERATIONS - START_VERSION + 1))
  est=$(estimate_cost $remaining)
  echo "[DRY RUN] Would run ${remaining} iterations, estimated cost: \$${est}"
  exit 0
fi

low_improvement_count=0
prev_score=0

# If resuming, recover prev_score from last eval
if [[ $START_VERSION -gt 1 ]]; then
  prev_eval="${EVAL_DIR}/v$((START_VERSION - 1))-eval.md"
  if [[ -f "$prev_eval" ]]; then
    prev_score=$(extract_score "$prev_eval" || echo "0")
  fi
fi

for i in $(seq $START_VERSION $MAX_ITERATIONS); do
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Iteration $i / $MAX_ITERATIONS"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Cost check
  completed=$((i - START_VERSION))
  spent=$(estimate_cost $completed)
  if (( $(echo "$spent > $MAX_COST_USD" | bc -l) )); then
    echo "Cost cap reached (\$${spent} > \$${MAX_COST_USD}). Stopping."
    break
  fi

  # ─── Step 1: Generator ───
  echo ""
  echo "  [Step 1/4] Running Generator..."
  run_generator $i || {
    echo "  Generator failed. Retrying once..."
    sleep 5
    run_generator $i || {
      echo "  Generator failed twice. Stopping."
      append_progress_simple $i "ERROR" "Generator failure"
      break
    }
  }

  # ─── Step 2: Frozen file check ───
  echo ""
  echo "  [Step 2/4] Checking frozen files..."
  cd "$REPO_ROOT"
  frozen_violations=0
  check_frozen_files || frozen_violations=$?
  if [[ $frozen_violations -gt 0 ]]; then
    echo "  WARNING: ${frozen_violations} frozen file(s) were reverted."
  fi

  # ─── Step 3: Validation (TypeScript) ───
  echo ""
  echo "  [Step 3/4] Running validation..."
  if ! run_validation; then
    echo "  TSC FAILED. Reverting generator changes for v${i}."
    cd "$REPO_ROOT"
    git checkout -- "solutions/business/edu-platform/frontend/src/"
    append_progress_simple "$i" "0" "TSC compilation failure"
    prev_score=0
    continue
  fi

  # ─── Git snapshot: after generator ───
  cd "$REPO_ROOT"
  git add "solutions/business/edu-platform/frontend/" \
          "${CHANGELOG_DIR}/" 2>/dev/null || true
  git commit -m "feat(frontend): lesson-template v${i} iteration" --allow-empty 2>/dev/null || true

  # ─── Step 4: Evaluator ───
  echo ""
  echo "  [Step 4/4] Running Evaluator..."
  run_evaluator $i || {
    echo "  Evaluator failed. Retrying once..."
    sleep 5
    run_evaluator $i || {
      echo "  Evaluator failed twice. Stopping."
      append_progress_simple $i "ERROR" "Evaluator failure"
      break
    }
  }

  # ─── Extract results + exit conditions ───
  echo ""
  echo "  Extracting results..."

  eval_file="${EVAL_DIR}/v${i}-eval.md"
  if [[ ! -f "$eval_file" ]]; then
    misnamed=$(ls -t "${EVAL_DIR}"/v*-eval.md 2>/dev/null | head -1)
    if [[ -n "$misnamed" ]] && [[ "$misnamed" != "${EVAL_DIR}/v$((i-1))-eval.md" ]]; then
      echo "  Eval report written as $(basename "$misnamed") instead of v${i}-eval.md — renaming."
      mv "$misnamed" "$eval_file"
    fi
  fi
  if [[ ! -f "$eval_file" ]]; then
    echo "  Eval report not found at ${eval_file}. Stopping."
    append_progress_simple $i "ERROR" "No eval report"
    break
  fi

  score=$(extract_score "$eval_file")
  if [[ -z "$score" ]]; then
    echo "  Could not extract score from eval report. Stopping."
    append_progress_simple $i "ERROR" "Score extraction failed"
    break
  fi

  # Extract per-dimension scores
  d1=$(extract_dim "D1" "$eval_file" || echo "-")
  d2=$(extract_dim "D2" "$eval_file" || echo "-")
  d3=$(extract_dim "D3" "$eval_file" || echo "-")
  d4=$(extract_dim "D4" "$eval_file" || echo "-")
  d5=$(extract_dim "D5" "$eval_file" || echo "-")

  # Extract top issue
  top_issue=$(grep -A1 "Priority Fix" "$eval_file" 2>/dev/null | tail -1 | cut -c1-60 || echo "N/A")

  append_progress "$i" "$score" "$d1" "$d2" "$d3" "$d4" "$d5" "$top_issue"
  echo "  Score: ${score}/100"

  # Git snapshot: eval
  cd "$REPO_ROOT"
  git add "${EVAL_DIR}/" "${PROGRESS_FILE}" 2>/dev/null || true
  git commit -m "feat(frontend): lesson-template v${i} eval — score ${score}/100" --allow-empty 2>/dev/null || true

  # ─── Exit conditions ───

  # 1. Score threshold
  if [[ "$score" -ge "$SCORE_THRESHOLD" ]]; then
    echo ""
    echo "  Score threshold reached! (${score} >= ${SCORE_THRESHOLD})"
    break
  fi

  # 2. Regression detection
  if [[ $prev_score -gt 0 && $score -lt $((prev_score - ROLLBACK_THRESHOLD)) ]]; then
    echo ""
    echo "  REGRESSION detected: ${prev_score} -> ${score}. Reverting source files."
    cd "$REPO_ROOT"
    git checkout HEAD~2 -- \
      "solutions/business/edu-platform/frontend/src/components/editor/" \
      "solutions/business/edu-platform/frontend/src/components/template/" \
      "solutions/business/edu-platform/frontend/src/pages/LessonPlanList.tsx" \
      "solutions/business/edu-platform/frontend/src/pages/LessonPlanEditor.tsx" \
      "solutions/business/edu-platform/frontend/src/pages/TemplateList.tsx" \
      "solutions/business/edu-platform/frontend/src/pages/TemplateEditor.tsx" \
      "solutions/business/edu-platform/frontend/src/types/lesson-plan.ts" \
      "solutions/business/edu-platform/frontend/src/types/template.ts" \
      "solutions/business/edu-platform/frontend/src/App.tsx" \
      "solutions/business/edu-platform/frontend/package.json" 2>/dev/null || true
    git add "solutions/business/edu-platform/frontend/" && \
    git commit -m "feat(frontend): lesson-template v${i} REVERTED — regression ${prev_score}->${score}" 2>/dev/null || true
    continue
  fi

  # 3. Diminishing returns
  if [[ $prev_score -gt 0 ]]; then
    improvement=$((score - prev_score))
    if [[ $improvement -lt $MIN_IMPROVEMENT ]]; then
      low_improvement_count=$((low_improvement_count + 1))
      if [[ $low_improvement_count -ge 2 ]]; then
        echo ""
        echo "  Diminishing returns (< ${MIN_IMPROVEMENT} pts for 2 consecutive iterations). Stopping."
        echo "  Bottleneck: ${top_issue}"
        break
      fi
      echo "  Low improvement (${improvement} pts). Count: ${low_improvement_count}/2"
    else
      low_improvement_count=0
    fi
  fi

  prev_score=$score
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Run Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Progress:  ${PROGRESS_FILE}"
echo "  Frontend:  solutions/business/edu-platform/frontend/src/"
echo "  History:   git log --grep='lesson-template' --oneline"
echo ""
echo "  Next steps:"
echo "    cat ${PROGRESS_FILE}"
echo "    cd solutions/business/edu-platform/frontend && npx tsc --noEmit"
echo "    npm run dev  # then open http://localhost:5173/lesson-plans"
echo ""
