#!/usr/bin/env bash
set -eu

# ============================================================
# Backend API Harness — TypeORM + NestJS Modules
# Generated by overnight-harness-builder (Code Mode)
# ============================================================

# --- Nested Session Guard ---
# Required when harness is launched from inside a Claude Code session.
# env -u is more reliable than unset in sandboxed environments.
claude_safe() {
  env -u CLAUDECODE \
      -u CLAUDE_CODE_ENTRYPOINT \
      -u CLAUDE_CODE_DISABLE_TERMINAL_TITLE \
      -u CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS \
      claude "$@"
}

# --- Configuration ---
TASK_NAME="backend-api"
MAX_ITERATIONS=8
SCORE_THRESHOLD=90
MIN_IMPROVEMENT=3
ROLLBACK_THRESHOLD=5
MAX_COST_USD="${MAX_COST:-100}"

# Agent tool permissions
GENERATOR_TOOLS="Read,Write,Edit,Grep,Glob,Bash"
EVALUATOR_TOOLS="Read,Write,Grep,Glob,Bash"

COST_PER_ITERATION=4.00  # estimate: NestJS backend scope

# --- Directories ---
REPO_ROOT="$(cd "$(dirname "$0")/../../../../../.." && pwd)"
SOLUTION_DIR="${REPO_ROOT}/solutions/business/edu-platform"
BACKEND_DIR="${SOLUTION_DIR}/backend"
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
EVAL_DIR="${HARNESS_DIR}/eval-reports"
CHANGELOG_DIR="${HARNESS_DIR}/changelogs"
PROMPTS_DIR="${HARNESS_DIR}/prompts"
PROGRESS_FILE="${HARNESS_DIR}/progress.md"

# Frozen paths (must NOT be modified by generator)
FROZEN_PATHS=(
  "solutions/business/edu-platform/backend/src/database/"
  "solutions/business/edu-platform/backend/src/curriculum/"
  "solutions/business/edu-platform/backend/src/users/"
  "solutions/business/edu-platform/backend/src/auth/"
  "solutions/business/edu-platform/backend/data/edu.db"
  "solutions/business/edu-platform/frontend/"
  "solutions/business/edu-platform/mcp-server/"
  "solutions/business/edu-platform/skills/"
)

# --- Flags ---
DRY_RUN=false
RESUME=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true ;;
    --resume) RESUME=true ;;
    --max-cost) shift; MAX_COST_USD="$1" ;;
    --max-cost=*) MAX_COST_USD="${1#*=}" ;;
  esac
  shift
done

# --- Functions ---

get_last_version() {
  local last=$(ls "${EVAL_DIR}"/v*-eval.md 2>/dev/null | sort -V | tail -1)
  if [[ -n "$last" ]]; then
    basename "$last" | sed 's/[^0-9]//g'
  else
    echo "0"
  fi
}

extract_score() {
  local eval_file="$1"
  local score
  # Primary: find "总分" or "Total" line with "XX/100" (most specific)
  score=$(grep -E '(^##[[:space:]]*)?总分|Total' "$eval_file" | grep -oE '[0-9]+/100' | head -1 | cut -d/ -f1)
  if [[ -n "$score" ]]; then
    echo "$score"
    return
  fi
  # Fallback: first "XX/100" in top 20 lines (avoid stray predictions near EOF)
  score=$(head -20 "$eval_file" | grep -oE '[0-9]+/100' | head -1 | cut -d/ -f1)
  if [[ -n "$score" ]]; then
    echo "$score"
    return
  fi
  # Last resort: any "总分" or "Total" line
  grep -E '(总分|Total)[：:][[:space:]]*[0-9]+' "$eval_file" | head -1 | grep -oE '[0-9]+' | head -1
}

estimate_cost() {
  local iterations=$1
  echo "scale=2; $iterations * $COST_PER_ITERATION" | bc
}

append_progress() {
  local version=$1 score=$2 d1=$3 d2=$4 d3=$5 d4=$6 d5=$7 d6=$8 top_issue=$9
  local timestamp=$(date '+%Y-%m-%d %H:%M')
  echo "| v${version} | ${timestamp} | ${score} | ${d1} | ${d2} | ${d3} | ${d4} | ${d5} | ${d6} | ${top_issue} |" >> "$PROGRESS_FILE"
}

append_progress_simple() {
  local version=$1 score=$2 top_issue=$3
  local timestamp=$(date '+%Y-%m-%d %H:%M')
  echo "| v${version} | ${timestamp} | ${score} | - | - | - | - | - | - | ${top_issue} |" >> "$PROGRESS_FILE"
}

check_frozen_files() {
  local violations=0
  cd "$REPO_ROOT"
  for frozen_path in "${FROZEN_PATHS[@]}"; do
    local changed
    changed=$(git diff --name-only | grep "^${frozen_path}" 2>/dev/null | wc -l | tr -d ' ')
    if [[ "$changed" -gt 0 ]]; then
      echo "  FROZEN PATH VIOLATION: ${frozen_path} has ${changed} modified file(s). Reverting."
      git diff --name-only | grep "^${frozen_path}" | xargs -I{} git checkout -- "{}"
      violations=$((violations + changed))
    fi
  done
  return $violations
}

stop_backend() {
  # Kill any process on port 3011
  local pids
  pids=$(lsof -ti:3011 2>/dev/null || true)
  if [[ -n "$pids" ]]; then
    echo "$pids" | xargs kill 2>/dev/null || true
    sleep 2
  fi
}

run_validation() {
  echo "  [Validation] Installing dependencies..."
  cd "$BACKEND_DIR"
  npm install 2>&1 | tail -3

  echo "  [Validation] TypeScript build..."
  if npm run build 2>&1; then
    echo "  [Validation] BUILD PASS"
    return 0
  else
    echo "  [Validation] BUILD FAIL — Generator must fix before eval"
    return 1
  fi
}

start_backend_for_eval() {
  stop_backend

  cd "$BACKEND_DIR"

  # Run seed if script exists
  if [[ -f "src/seed-typeorm.ts" ]]; then
    echo "  [Eval Prep] Running seed..."
    npx ts-node src/seed-typeorm.ts 2>&1 | tail -3 || echo "  [Eval Prep] Seed script failed (may not be critical)"
  fi

  # Start backend in background
  echo "  [Eval Prep] Starting backend on port 3011..."
  npm run start:dev > /tmp/backend-harness.log 2>&1 &
  BACKEND_PID=$!

  # Wait for backend to be ready (max 30 seconds)
  local retries=0
  while [[ $retries -lt 30 ]]; do
    if curl -sf http://localhost:3011/api/curriculum/subjects > /dev/null 2>&1; then
      echo "  [Eval Prep] Backend ready (PID ${BACKEND_PID})"
      return 0
    fi
    sleep 1
    retries=$((retries + 1))
  done

  echo "  [Eval Prep] Backend failed to start within 30s"
  cat /tmp/backend-harness.log | tail -20
  return 1
}

run_generator() {
  local version=$1
  local prev=$((version - 1))
  local prompt=$(cat "$PROMPTS_DIR/generator.md")

  # Replace {N} and {N-1} placeholders in base prompt
  prompt="${prompt//\{N-1\}/${prev}}"
  prompt="${prompt//\{N\}/${version}}"

  if [[ $version -eq 1 ]]; then
    prompt="${prompt}

---
## Iteration Context (injected by orchestrator)

This is the **FIRST** iteration (v1). Create all files from scratch.

**Your starting point**: No TypeORM integration, no new modules. Create:
1. Install dependencies: \`typeorm @nestjs/typeorm sqlite3\`
2. Create TypeORM config module in \`backend/src/typeorm/\`
3. Create 6 Entity files in \`backend/src/entities/\`
4. Create 4 modules: lesson-plan, template, dashboard, activity
5. Create seed script \`backend/src/seed-typeorm.ts\`
6. Update \`backend/src/app.module.ts\` to register new modules

**Priority**: Get \`npm run build\` to pass first. Then seed data. Then endpoint completeness.

**Save changelog to**: ${CHANGELOG_DIR}/v1-changelog.md"
  else
    prompt="${prompt}

---
## Iteration Context (injected by orchestrator)

This is iteration **v${version}**.

**Your starting point**: Read existing files in \`backend/src/\` — they have been modified by prior iterations. Continue from here, DO NOT recreate from scratch.

**Read the eval report**: \`harness-workspace/main-page-and-lesson-plan/backend-api/eval-reports/v${prev}-eval.md\` — it tells you exactly what to fix.

**Save changelog to**: ${CHANGELOG_DIR}/v${version}-changelog.md"
  fi

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$GENERATOR_TOOLS" 2>&1 || {
    echo "ERROR: Generator failed on v${version}" >&2
    return 1
  }
}

run_evaluator() {
  local version=$1
  local prompt=$(cat "$PROMPTS_DIR/evaluator.md")

  # Inject version number using bash parameter expansion (safer than sed)
  prompt="${prompt//\{N\}/${version}}"

  cd "$REPO_ROOT"
  claude_safe -p "$prompt" --allowedTools "$EVALUATOR_TOOLS" 2>&1 || {
    echo "ERROR: Evaluator failed on v${version}" >&2
    return 1
  }
}

extract_dim() {
  local dim="$1" file="$2"
  grep "| ${dim} |" "$file" 2>/dev/null | head -1 | awk -F'|' '{gsub(/[[:space:]]/, "", $4); split($4, a, "/"); print a[1]}'
}

# --- Pre-flight ---

command -v bc >/dev/null 2>&1 || { echo "ERROR: 'bc' is required but not installed."; exit 1; }

mkdir -p "$EVAL_DIR" "$CHANGELOG_DIR"

# --- Main Loop ---

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  ${TASK_NAME} Harness — TypeORM + NestJS Backend             ║"
echo "║  Artifact: backend/src/ (TypeORM + 4 modules + 25 endpoints) ║"
echo "║  Dimensions: D1-D6 (Entity/API/Logic/Seed/Integration/Code)  ║"
echo "║  Max iterations: ${MAX_ITERATIONS}                            ║"
echo "║  Score threshold: ${SCORE_THRESHOLD}/100                      ║"
echo "║  Cost cap: \$${MAX_COST_USD}                                  ║"
echo "╚══════════════════════════════════════════════════════════════╝"

if $RESUME; then
  START_VERSION=$(( $(get_last_version) + 1 ))
  echo "Resuming from v${START_VERSION}..."
else
  START_VERSION=1
fi

if $DRY_RUN; then
  remaining=$((MAX_ITERATIONS - START_VERSION + 1))
  est=$(estimate_cost $remaining)
  echo "[DRY RUN] Would run ${remaining} iterations, estimated cost: \$${est}"
  exit 0
fi

low_improvement_count=0
prev_score=0

# If resuming, recover prev_score from last eval
if [[ $START_VERSION -gt 1 ]]; then
  prev_eval="${EVAL_DIR}/v$((START_VERSION - 1))-eval.md"
  if [[ -f "$prev_eval" ]]; then
    prev_score=$(extract_score "$prev_eval" || echo "0")
  fi
fi

# Ensure cleanup on exit
trap 'stop_backend' EXIT

for i in $(seq $START_VERSION $MAX_ITERATIONS); do
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Iteration $i / $MAX_ITERATIONS"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  # Cost check
  completed=$((i - START_VERSION))
  spent=$(estimate_cost $completed)
  if (( $(echo "$spent > $MAX_COST_USD" | bc -l) )); then
    echo "Cost cap reached (\$${spent} > \$${MAX_COST_USD}). Stopping."
    break
  fi

  # ─── Step 1: Generator ───
  echo ""
  echo "  [Step 1/5] Running Generator..."
  run_generator $i || {
    echo "  Generator failed. Retrying once..."
    sleep 5
    run_generator $i || {
      echo "  Generator failed twice. Stopping."
      append_progress_simple $i "ERROR" "Generator failure"
      break
    }
  }

  # ─── Step 2: Frozen file check ───
  echo ""
  echo "  [Step 2/5] Checking frozen files..."
  cd "$REPO_ROOT"
  frozen_violations=0
  check_frozen_files || frozen_violations=$?
  if [[ $frozen_violations -gt 0 ]]; then
    echo "  WARNING: ${frozen_violations} frozen file(s) were reverted."
  fi

  # ─── Step 3: Validation (build) ───
  echo ""
  echo "  [Step 3/5] Running validation..."
  if ! run_validation; then
    echo "  BUILD FAILED. Reverting generator changes for v${i}."
    cd "$REPO_ROOT"
    git checkout -- "solutions/business/edu-platform/backend/src/"
    append_progress_simple "$i" "0" "Build compilation failure"
    prev_score=0
    continue
  fi

  # ─── Git snapshot: after generator ───
  cd "$REPO_ROOT"
  git add "solutions/business/edu-platform/backend/" \
          "${CHANGELOG_DIR}/" 2>/dev/null || true
  git commit -m "feat(backend): backend-api v${i} iteration" --allow-empty 2>/dev/null || true

  # ─── Step 4: Start backend + Evaluator ───
  echo ""
  echo "  [Step 4/5] Starting backend for evaluation..."
  start_backend_for_eval || {
    echo "  Backend failed to start. Evaluator will handle gracefully."
  }

  echo ""
  echo "  [Step 4/5] Running Evaluator..."
  run_evaluator $i || {
    echo "  Evaluator failed. Retrying once..."
    sleep 5
    run_evaluator $i || {
      echo "  Evaluator failed twice. Stopping."
      stop_backend
      append_progress_simple $i "ERROR" "Evaluator failure"
      break
    }
  }

  # Stop backend after eval
  stop_backend

  # ─── Step 5: Extract results + exit conditions ───
  echo ""
  echo "  [Step 5/5] Extracting results..."

  eval_file="${EVAL_DIR}/v${i}-eval.md"
  if [[ ! -f "$eval_file" ]]; then
    # Safety net: evaluator may have used a wrong version number
    misnamed=$(ls -t "${EVAL_DIR}"/v*-eval.md 2>/dev/null | head -1)
    if [[ -n "$misnamed" ]] && [[ "$misnamed" != "${EVAL_DIR}/v$((i-1))-eval.md" ]]; then
      echo "  Eval report written as $(basename "$misnamed") instead of v${i}-eval.md — renaming."
      mv "$misnamed" "$eval_file"
    fi
  fi
  if [[ ! -f "$eval_file" ]]; then
    echo "  Eval report not found at ${eval_file}. Stopping."
    append_progress_simple $i "ERROR" "No eval report"
    break
  fi

  score=$(extract_score "$eval_file")
  if [[ -z "$score" ]]; then
    echo "  Could not extract score from eval report. Stopping."
    append_progress_simple $i "ERROR" "Score extraction failed"
    break
  fi

  # Extract per-dimension scores
  d1=$(extract_dim "D1" "$eval_file" || echo "-")
  d2=$(extract_dim "D2" "$eval_file" || echo "-")
  d3=$(extract_dim "D3" "$eval_file" || echo "-")
  d4=$(extract_dim "D4" "$eval_file" || echo "-")
  d5=$(extract_dim "D5" "$eval_file" || echo "-")
  d6=$(extract_dim "D6" "$eval_file" || echo "-")

  # Extract top issue
  top_issue=$(grep -A1 "Priority Fix" "$eval_file" 2>/dev/null | tail -1 | cut -c1-60 || echo "N/A")

  append_progress "$i" "$score" "$d1" "$d2" "$d3" "$d4" "$d5" "$d6" "$top_issue"
  echo "  Score: ${score}/100"

  # Git snapshot: eval
  cd "$REPO_ROOT"
  git add "${EVAL_DIR}/" "${PROGRESS_FILE}" 2>/dev/null || true
  git commit -m "feat(backend): backend-api v${i} eval — score ${score}/100" --allow-empty 2>/dev/null || true

  # ─── Exit conditions ───

  # 1. Score threshold
  if [[ "$score" -ge "$SCORE_THRESHOLD" ]]; then
    echo ""
    echo "  Score threshold reached! (${score} >= ${SCORE_THRESHOLD})"
    break
  fi

  # 2. Regression detection
  if [[ $prev_score -gt 0 && $score -lt $((prev_score - ROLLBACK_THRESHOLD)) ]]; then
    echo ""
    echo "  REGRESSION detected: ${prev_score} -> ${score}. Reverting source files."
    cd "$REPO_ROOT"
    git checkout HEAD~2 -- \
      "solutions/business/edu-platform/backend/src/typeorm/" \
      "solutions/business/edu-platform/backend/src/entities/" \
      "solutions/business/edu-platform/backend/src/lesson-plan/" \
      "solutions/business/edu-platform/backend/src/template/" \
      "solutions/business/edu-platform/backend/src/dashboard/" \
      "solutions/business/edu-platform/backend/src/activity/" \
      "solutions/business/edu-platform/backend/src/seed-typeorm.ts" \
      "solutions/business/edu-platform/backend/src/app.module.ts" 2>/dev/null || true
    git add "solutions/business/edu-platform/backend/" && \
    git commit -m "feat(backend): backend-api v${i} REVERTED — regression ${prev_score}->${score}" 2>/dev/null || true
    continue
  fi

  # 3. Diminishing returns
  if [[ $prev_score -gt 0 ]]; then
    improvement=$((score - prev_score))
    if [[ $improvement -lt $MIN_IMPROVEMENT ]]; then
      low_improvement_count=$((low_improvement_count + 1))
      if [[ $low_improvement_count -ge 2 ]]; then
        echo ""
        echo "  Diminishing returns (< ${MIN_IMPROVEMENT} pts for 2 consecutive iterations). Stopping."
        echo "  Bottleneck: ${top_issue}"
        break
      fi
      echo "  Low improvement (${improvement} pts). Count: ${low_improvement_count}/2"
    else
      low_improvement_count=0
    fi
  fi

  prev_score=$score
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Run Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Progress:  ${PROGRESS_FILE}"
echo "  Backend:   solutions/business/edu-platform/backend/src/"
echo "  History:   git log --grep='backend-api' --oneline"
echo ""
echo "  Next steps:"
echo "    cat ${PROGRESS_FILE}"
echo "    cd solutions/business/edu-platform/backend && npm run build"
echo "    npm run start:dev  # then curl http://localhost:3011/api/lesson-plans"
echo ""
