// Re-export all types from common/ (single source of truth)
export {
  SYNC_FIELDS,
  type SyncField,
  type KnowledgePointTag,
  type SolutionStep,
  type Mistake,
  type RelatedQuiz,
  type KpRefinementTag,
  type KpRefinementResult,
  type WriteOutputInput,
  type WriteOutputResult,
  type KnowledgePointNode,
  ErrorType,
  type ErrorStep,
  type StudentAnswer,
  type ErrorTypeMatch,
  type EnhancedRelatedQuiz,
  type ErrorPattern,
} from './common/types.js';
