/**
 * PDF Generator - Create LEGO assembly guide PDFs using PDFKit
 *
 * Generates:
 * - Cover page with title, dimensions, and total brick count
 * - Bill of Materials page with color swatches
 * - Assembly pages showing brick placement per region (8x8 grid sections)
 * - BrickLink XML wanted list on the last page
 */

import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';
import { getColorById, getBrickById } from './lego-catalog.js';
import type { Placement, BillItem, MosaicConfig } from './types.js';

interface PdfResult {
  pdfPath: string;
  pageCount: number;
  downloadUrl: string;
}

const PAGE_WIDTH = 595.28; // A4
const PAGE_HEIGHT = 841.89;
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
const STUD_SIZE = 12; // pixels per stud in assembly view
const SECTION_SIZE = 8; // 8x8 stud sections for assembly pages

/**
 * Generate BrickLink XML wanted list
 */
function generateBrickLinkXml(bom: BillItem[]): string {
  const items = bom
    .map(
      (item) =>
        `  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>${item.brickId}</ITEMID>
    <COLOR>${item.colorId}</COLOR>
    <MINQTY>${item.quantity}</MINQTY>
  </ITEM>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>\n<INVENTORY>\n${items}\n</INVENTORY>`;
}

/**
 * Draw a LEGO stud (circle on top of a colored rectangle)
 */
function drawStud(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  size: number,
  hex: string
): void {
  // Brick background
  doc.rect(x, y, size, size).fill(hex);

  // Border
  doc.rect(x, y, size, size).lineWidth(0.3).stroke('#888888');

  // Stud circle (lighter shade)
  const cx = x + size / 2;
  const cy = y + size / 2;
  const r = size * 0.25;
  doc.circle(cx, cy, r).lineWidth(0.5).stroke('#AAAAAA');
}

/**
 * Generate the assembly guide PDF
 */
export async function generateAssemblyPdf(
  placements: Placement[],
  bom: BillItem[],
  config: MosaicConfig,
  title: string = 'LEGO Mosaic Assembly Guide',
  outputDir: string
): Promise<PdfResult> {
  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const filename = `assembly-guide-${Date.now()}.pdf`;
  const pdfPath = path.join(outputDir, filename);
  let pageCount = 0;

  return new Promise<PdfResult>((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
      info: {
        Title: title,
        Author: 'LEGO Playground - AI Mosaic Designer',
        Subject: 'LEGO Mosaic Assembly Guide',
      },
    });

    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    // ==========================================
    // PAGE 1: Cover
    // ==========================================
    pageCount++;

    doc.fontSize(28).font('Helvetica-Bold').text(title, MARGIN, 120, {
      align: 'center',
      width: CONTENT_WIDTH,
    });

    doc.moveDown(2);
    doc.fontSize(14).font('Helvetica').text('LEGO Mosaic Assembly Guide', {
      align: 'center',
      width: CONTENT_WIDTH,
    });

    doc.moveDown(3);

    // Stats box
    const statsY = 320;
    doc.rect(MARGIN + 100, statsY, CONTENT_WIDTH - 200, 180).lineWidth(1).stroke('#333333');

    const statsContent = [
      `Dimensions: ${config.widthStuds} x ${config.heightStuds} studs`,
      `Layers: ${config.layerCount}`,
      `Total Bricks: ${placements.length.toLocaleString()}`,
      `Unique Colors: ${new Set(placements.map((p) => p.colorId)).size}`,
      `Unique Parts: ${bom.length}`,
    ];

    doc.fontSize(13).font('Helvetica');
    statsContent.forEach((line, i) => {
      doc.text(line, MARGIN + 120, statsY + 25 + i * 30, {
        width: CONTENT_WIDTH - 240,
      });
    });

    doc
      .fontSize(10)
      .fillColor('#888888')
      .text(
        `Generated by LEGO Playground on ${new Date().toLocaleDateString()}`,
        MARGIN,
        PAGE_HEIGHT - MARGIN - 30,
        { align: 'center', width: CONTENT_WIDTH }
      );

    doc.fillColor('#000000');

    // ==========================================
    // PAGE 2: Bill of Materials
    // ==========================================
    doc.addPage();
    pageCount++;

    doc.fontSize(20).font('Helvetica-Bold').text('Bill of Materials', MARGIN, MARGIN);
    doc.moveDown(1);

    // Table header
    const tableTop = doc.y;
    const colWidths = [30, 120, 100, 100, 80, 85];
    const headers = ['#', 'Color', 'Brick', 'Size', 'Qty', 'BrickLink ID'];

    doc.fontSize(9).font('Helvetica-Bold');
    let xPos = MARGIN;
    headers.forEach((h, i) => {
      doc.text(h, xPos, tableTop, { width: colWidths[i] });
      xPos += colWidths[i];
    });

    doc.moveTo(MARGIN, tableTop + 15).lineTo(PAGE_WIDTH - MARGIN, tableTop + 15).stroke();

    // Table rows
    doc.font('Helvetica').fontSize(8);
    let rowY = tableTop + 20;
    const maxRowsPerPage = 45;
    let rowCount = 0;

    for (let i = 0; i < bom.length; i++) {
      if (rowCount >= maxRowsPerPage) {
        doc.addPage();
        pageCount++;
        rowY = MARGIN + 20;
        rowCount = 0;

        // Repeat header
        doc.fontSize(9).font('Helvetica-Bold');
        xPos = MARGIN;
        headers.forEach((h, j) => {
          doc.text(h, xPos, MARGIN, { width: colWidths[j] });
          xPos += colWidths[j];
        });
        doc.moveTo(MARGIN, MARGIN + 15).lineTo(PAGE_WIDTH - MARGIN, MARGIN + 15).stroke();
        doc.font('Helvetica').fontSize(8);
      }

      const item = bom[i];
      const color = getColorById(item.colorId);
      const brick = getBrickById(item.brickId);

      // Color swatch
      if (color) {
        doc.rect(MARGIN + 2, rowY, 10, 10).fill(color.hex).stroke('#999');
      }

      xPos = MARGIN;
      const rowData = [
        `${i + 1}`,
        color?.name || `Color ${item.colorId}`,
        brick?.name || item.brickId,
        brick ? `${brick.widthStuds}x${brick.heightStuds}` : '-',
        `${item.quantity}`,
        `${item.brickId} / C${item.colorId}`,
      ];

      rowData.forEach((text, j) => {
        const textX = j === 0 ? xPos + 15 : xPos;
        doc.fillColor('#000000').text(text, textX, rowY, { width: colWidths[j] });
        xPos += colWidths[j];
      });

      rowY += 15;
      rowCount++;
    }

    // Total
    doc.moveDown(1);
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text(`Total: ${placements.length.toLocaleString()} bricks`, MARGIN, rowY + 10);

    // ==========================================
    // ASSEMBLY PAGES: Section-by-section placement
    // ==========================================
    const sectionsX = Math.ceil(config.widthStuds / SECTION_SIZE);
    const sectionsY = Math.ceil(config.heightStuds / SECTION_SIZE);

    for (let layer = 0; layer < config.layerCount; layer++) {
      const layerPlacements = placements.filter((p) => p.layer === layer);

      for (let sy = 0; sy < sectionsY; sy++) {
        for (let sx = 0; sx < sectionsX; sx++) {
          doc.addPage();
          pageCount++;

          const sectionLabel = `Layer ${layer + 1} - Section (${sx + 1}, ${sy + 1})`;
          doc.fontSize(14).font('Helvetica-Bold').text(sectionLabel, MARGIN, MARGIN);

          doc
            .fontSize(9)
            .font('Helvetica')
            .text(
              `Studs ${sx * SECTION_SIZE}-${Math.min((sx + 1) * SECTION_SIZE, config.widthStuds) - 1} x ${sy * SECTION_SIZE}-${Math.min((sy + 1) * SECTION_SIZE, config.heightStuds) - 1}`,
              MARGIN,
              MARGIN + 20
            );

          const gridStartX = MARGIN + 20;
          const gridStartY = MARGIN + 50;
          const cellSize = Math.min(
            (CONTENT_WIDTH - 40) / SECTION_SIZE,
            (PAGE_HEIGHT - MARGIN * 2 - 120) / SECTION_SIZE,
            50
          );

          // Draw grid
          const startX = sx * SECTION_SIZE;
          const startY = sy * SECTION_SIZE;
          const endX = Math.min(startX + SECTION_SIZE, config.widthStuds);
          const endY = Math.min(startY + SECTION_SIZE, config.heightStuds);

          for (let y = startY; y < endY; y++) {
            for (let x = startX; x < endX; x++) {
              const placement = layerPlacements.find((p) => p.x === x && p.y === y);
              if (placement) {
                const color = getColorById(placement.colorId);
                const drawX = gridStartX + (x - startX) * cellSize;
                const drawY = gridStartY + (y - startY) * cellSize;
                drawStud(doc, drawX, drawY, cellSize, color?.hex || '#CCCCCC');

                // Show brick ID for larger bricks
                const brick = getBrickById(placement.brickId);
                if (brick && brick.widthStuds * brick.heightStuds > 1) {
                  doc
                    .fontSize(5)
                    .fillColor('#000000')
                    .text(placement.brickId, drawX + 1, drawY + cellSize - 8, {
                      width: cellSize - 2,
                    });
                }
              } else {
                // Empty cell
                const drawX = gridStartX + (x - startX) * cellSize;
                const drawY = gridStartY + (y - startY) * cellSize;
                doc.rect(drawX, drawY, cellSize, cellSize).lineWidth(0.2).stroke('#DDDDDD');
              }
            }
          }

          // Color legend for this section
          const legendY = gridStartY + (endY - startY) * cellSize + 20;
          const sectionColors = new Set(
            layerPlacements
              .filter(
                (p) =>
                  p.x >= startX && p.x < endX && p.y >= startY && p.y < endY
              )
              .map((p) => p.colorId)
          );

          doc.fontSize(9).font('Helvetica-Bold').text('Colors in this section:', MARGIN, legendY);
          let legendX = MARGIN;
          let legendRow = legendY + 15;

          for (const colorId of sectionColors) {
            const color = getColorById(colorId);
            if (color) {
              if (legendX + 100 > PAGE_WIDTH - MARGIN) {
                legendX = MARGIN;
                legendRow += 15;
              }
              doc.rect(legendX, legendRow, 8, 8).fill(color.hex).stroke('#999');
              doc
                .fontSize(7)
                .fillColor('#000000')
                .text(color.name, legendX + 12, legendRow, { width: 80 });
              legendX += 100;
            }
          }
        }
      }
    }

    // ==========================================
    // LAST PAGE: BrickLink XML
    // ==========================================
    doc.addPage();
    pageCount++;

    doc.fontSize(16).font('Helvetica-Bold').text('BrickLink Wanted List', MARGIN, MARGIN);
    doc.moveDown(1);

    doc
      .fontSize(9)
      .font('Helvetica')
      .text(
        'Copy the XML below and import it into BrickLink to purchase all required bricks:',
        MARGIN
      );
    doc.moveDown(1);

    const xml = generateBrickLinkXml(bom);
    doc.fontSize(7).font('Courier').text(xml, MARGIN, doc.y, {
      width: CONTENT_WIDTH,
    });

    // Finalize
    doc.end();

    stream.on('finish', () => {
      resolve({
        pdfPath,
        pageCount,
        downloadUrl: `/api/downloads/${filename}`,
      });
    });

    stream.on('error', reject);
  });
}
