/**
 * Lesson Plan specific type definitions
 */

/**
 * A single section within textbook analysis
 */
export interface TextbookAnalysisSection {
  title: string
  content: string
}

/**
 * Structured textbook analysis value with 4 sub-modules
 * Generated by AI agent for the "教材分析" section
 */
export interface TextbookAnalysisValue {
  /** 教学内容的地位和作用 */
  coursePosition?: TextbookAnalysisSection
  /** 教学重点和难点分析 */
  keyPointsAnalysis?: TextbookAnalysisSection
  /** 教材内容的逻辑结构和知识关联 */
  logicalStructure?: TextbookAnalysisSection
  /** 教学策略建议 */
  teachingStrategies?: TextbookAnalysisSection
}

/**
 * Type guard to check if value is a TextbookAnalysisValue object
 */
export function isTextbookAnalysisValue(value: unknown): value is TextbookAnalysisValue {
  if (typeof value !== 'object' || value === null) {
    return false
  }
  const obj = value as Record<string, unknown>
  // Check for at least one of the expected properties with correct structure
  const hasValidSection = (key: string): boolean => {
    const section = obj[key]
    if (!section || typeof section !== 'object') return false
    const s = section as Record<string, unknown>
    return typeof s.title === 'string' && typeof s.content === 'string'
  }

  return (
    hasValidSection('coursePosition') ||
    hasValidSection('keyPointsAnalysis') ||
    hasValidSection('logicalStructure') ||
    hasValidSection('teachingStrategies')
  )
}

/**
 * Convert TextbookAnalysisValue to markdown string for display
 */
export function textbookAnalysisToMarkdown(value: TextbookAnalysisValue): string {
  const sections: string[] = []

  if (value.coursePosition) {
    sections.push(`### ${value.coursePosition.title}\n\n${value.coursePosition.content}`)
  }
  if (value.keyPointsAnalysis) {
    sections.push(`### ${value.keyPointsAnalysis.title}\n\n${value.keyPointsAnalysis.content}`)
  }
  if (value.logicalStructure) {
    sections.push(`### ${value.logicalStructure.title}\n\n${value.logicalStructure.content}`)
  }
  if (value.teachingStrategies) {
    sections.push(`### ${value.teachingStrategies.title}\n\n${value.teachingStrategies.content}`)
  }

  return sections.join('\n\n')
}
