export const OBSERVER_ENGINE = 'OBSERVER_ENGINE';
export const OBSERVER_HANDLER_METADATA = 'OBSERVER_HANDLER_METADATA';
export const OBSERVER_ENGINE_OPTIONS = 'OBSERVER_ENGINE_OPTIONS';
export const OBSERVER_LLM_GATEWAY = 'OBSERVER_LLM_GATEWAY';
export const OBSERVER_NOTIFY_SINK = 'OBSERVER_NOTIFY_SINK';
