#!/usr/bin/env bash
set -eu

# Allow nested claude -p invocations from within a Claude Code session
unset CLAUDECODE 2>/dev/null || true

# ============================================================
# Context Layer @ Reference Picker — Harness Orchestrator
# Generated by overnight-harness-builder (Code Mode)
# ============================================================
# Usage:
#   ./harness.sh              # Run from v0
#   ./harness.sh --resume     # Continue from last iteration
#   ./harness.sh --dry-run    # Show plan without running
#   ./harness.sh --max-cost 20 # Stop if estimated cost exceeds $20

# --- Configuration ---
TASK_NAME="context-layer-reference-picker"
MAX_ITERATIONS=12
TARGET_SCORE=90
DIMINISHING_THRESHOLD=3
DIMINISHING_MAX_STALLS=3
COST_PER_ITERATION=12.00
ROLLBACK_THRESHOLD=5
FATAL_PENALTY_MAX_CONSECUTIVE=2

# Ports
MOCK_BACKEND_PORT=3021
CHAT_INTERFACE_PORT=5173

# --- Directories ---
HARNESS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$HARNESS_DIR/../.." && pwd)"
CONTEXT_LAYER="$PROJECT_ROOT/packages/context-layer"
CONTEXT_LAYER_REACT="$PROJECT_ROOT/packages/context-layer-react"
CHAT_INTERFACE="$PROJECT_ROOT/packages/chat-interface"
MOCK_SOLUTION="$PROJECT_ROOT/solutions/mock/context-layer-demo"
E2E_DIR="$HARNESS_DIR/e2e"

EVAL_DIR="$HARNESS_DIR/eval-reports"
CHANGELOG_DIR="$HARNESS_DIR/changelogs"
PROMPTS_DIR="$HARNESS_DIR/prompts"
PROGRESS_FILE="$HARNESS_DIR/progress.md"
SCREENSHOTS_DIR="$HARNESS_DIR/screenshots"

# --- Agent Tools ---
GENERATOR_TOOLS="Read,Write,Edit,Grep,Glob,Bash"
EVALUATOR_TOOLS="Read,Grep,Glob,Bash"

# --- Frozen Files ---
FROZEN_FILES="packages/chat-interface/src/components/chat/ChatInterfaceComposer.tsx"

# --- Flags ---
DRY_RUN=false
RESUME=false
MAX_COST=120

while [[ $# -gt 0 ]]; do
  case $1 in
    --resume) RESUME=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    --max-cost) MAX_COST="$2"; shift 2 ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# --- Helpers ---

log() { echo "[$(date '+%H:%M:%S')] $*"; }
err() { echo "[$(date '+%H:%M:%S')] ERROR: $*" >&2; }

check_port() {
  nc -z localhost "$1" 2>/dev/null
}

extract_score() {
  local report="$1"
  local score
  score=$(grep -oE '(总分|Total)[：:]\s*[0-9]+\.?[0-9]*/100' "$report" | tail -1 | grep -oE '[0-9]+\.?[0-9]*' | head -1)
  score=$(printf '%.0f' "${score:-0}")
  echo "${score:-0}"
}

get_last_version() {
  local last
  last=$(grep -oE '\| v[0-9]+' "$PROGRESS_FILE" 2>/dev/null | tail -1 | grep -oE '[0-9]+')
  echo "${last:-0}"
}

# --- Frozen file violation gate ---
check_frozen_files() {
  local violations=0
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    if (cd "$PROJECT_ROOT" && git diff --name-only | grep -qF "$f"); then
      log "FROZEN FILE VIOLATION: $f was modified. Reverting."
      (cd "$PROJECT_ROOT" && git checkout -- "$f")
      violations=$((violations + 1))
    fi
  done <<< "$FROZEN_FILES"
  return $violations
}

# --- Architecture violation checks ---
check_architecture() {
  local violations=0

  # P1: core/ must not import @nestjs
  if grep -rn "from '@nestjs" "$CONTEXT_LAYER/src/core/" 2>/dev/null | grep -v "node_modules" | head -5; then
    log "P1 VIOLATION: core/ imports @nestjs"
    violations=$((violations + 1))
  fi

  # P3: mock must not import edu-platform
  if grep -rn "from '.*edu-platform" "$MOCK_SOLUTION/" 2>/dev/null | grep -v "node_modules" | head -5; then
    log "P3 VIOLATION: mock imports edu-platform"
    violations=$((violations + 1))
  fi

  return $violations
}

# --- Dev server management ---
MOCK_PID=""
CHAT_PID=""

start_mock_solution() {
  if check_port "$MOCK_BACKEND_PORT"; then
    log "Mock solution already running on port $MOCK_BACKEND_PORT"
    return 0
  fi
  if [[ ! -d "$MOCK_SOLUTION" ]]; then
    log "Mock solution directory does not exist yet (first iteration will create it)"
    return 1
  fi
  log "Starting mock solution on port $MOCK_BACKEND_PORT..."
  (cd "$MOCK_SOLUTION" && npm run dev) &
  MOCK_PID=$!
  for i in $(seq 1 30); do
    if check_port "$MOCK_BACKEND_PORT"; then
      log "Mock solution ready on port $MOCK_BACKEND_PORT (PID: $MOCK_PID)"
      return 0
    fi
    sleep 1
  done
  err "Mock solution failed to start within 30s"
  kill $MOCK_PID 2>/dev/null || true
  MOCK_PID=""
  return 1
}

start_chat_interface() {
  if check_port "$CHAT_INTERFACE_PORT"; then
    log "Chat interface already running on port $CHAT_INTERFACE_PORT"
    return 0
  fi
  log "Starting chat interface on port $CHAT_INTERFACE_PORT..."
  (cd "$CHAT_INTERFACE" && VITE_CONTEXT_LAYER_URL=http://localhost:${MOCK_BACKEND_PORT}/context npx vite --port $CHAT_INTERFACE_PORT) &
  CHAT_PID=$!
  for i in $(seq 1 30); do
    if check_port "$CHAT_INTERFACE_PORT"; then
      log "Chat interface ready on port $CHAT_INTERFACE_PORT (PID: $CHAT_PID)"
      return 0
    fi
    sleep 1
  done
  err "Chat interface failed to start within 30s"
  kill $CHAT_PID 2>/dev/null || true
  CHAT_PID=""
  return 1
}

stop_servers() {
  if [[ -n "${MOCK_PID:-}" ]]; then
    log "Stopping mock solution (PID: $MOCK_PID)..."
    kill $MOCK_PID 2>/dev/null || true
    MOCK_PID=""
  fi
  if [[ -n "${CHAT_PID:-}" ]]; then
    log "Stopping chat interface (PID: $CHAT_PID)..."
    kill $CHAT_PID 2>/dev/null || true
    CHAT_PID=""
  fi
  # Also kill any processes on our ports
  lsof -ti:$MOCK_BACKEND_PORT 2>/dev/null | xargs kill 2>/dev/null || true
  lsof -ti:$CHAT_INTERFACE_PORT 2>/dev/null | xargs kill 2>/dev/null || true
}

cleanup() {
  stop_servers
}
trap cleanup EXIT

# --- Source file listing (for prompt context) ---
SOURCE_CONTEXT="
## 源代码目录
- Context Layer (core): $CONTEXT_LAYER/src/core/
- Context Layer (nestjs): $CONTEXT_LAYER/src/nestjs/
- Context Layer (client): $CONTEXT_LAYER/src/client/
- Context Layer React: $CONTEXT_LAYER_REACT/src/
- Chat Interface (mention): $CHAT_INTERFACE/src/components/chat/
- Mock Solution: $MOCK_SOLUTION/src/
- E2E Tests: $E2E_DIR/"

# ─────────────────────────────────────────────────────────
# Pre-flight
# ─────────────────────────────────────────────────────────

log "╔══════════════════════════════════════════════════════════╗"
log "║  Context Layer @ Reference Picker — Harness             ║"
log "║  Max iterations: $MAX_ITERATIONS                        ║"
log "║  Target score: $TARGET_SCORE/100                        ║"
log "║  Max cost: \$$MAX_COST                                   ║"
log "╚══════════════════════════════════════════════════════════╝"

# Ensure required files exist
for f in SPEC.md EVAL_CRITERIA.md prompts/generator.md prompts/evaluator.md progress.md; do
  if [[ ! -f "$HARNESS_DIR/$f" ]]; then
    err "Missing required file: $f"
    exit 1
  fi
done

# Ensure output directories exist
mkdir -p "$EVAL_DIR" "$CHANGELOG_DIR" "$SCREENSHOTS_DIR"

# Check claude CLI
if ! command -v claude &>/dev/null; then
  err "claude CLI not found. Install: https://docs.anthropic.com/claude-code"
  exit 1
fi

# Determine starting version
if $RESUME; then
  VERSION=$(get_last_version)
  log "Resuming from v$VERSION"
else
  VERSION=0
  log "Starting fresh from v0"
fi

if $DRY_RUN; then
  log ""
  log "[DRY RUN] Would run up to $MAX_ITERATIONS iterations"
  log "[DRY RUN] Estimated cost: ~\$$(echo "$MAX_ITERATIONS * $COST_PER_ITERATION" | bc)"
  log ""
  log "[DRY RUN] Source locations:"
  log "[DRY RUN]   context-layer: $CONTEXT_LAYER"
  log "[DRY RUN]   context-layer-react: $CONTEXT_LAYER_REACT"
  log "[DRY RUN]   chat-interface: $CHAT_INTERFACE"
  log "[DRY RUN]   mock solution: $MOCK_SOLUTION"
  log "[DRY RUN]   E2E tests: $E2E_DIR"
  log ""

  # Check if packages exist
  for dir in "$CONTEXT_LAYER" "$CONTEXT_LAYER_REACT" "$MOCK_SOLUTION"; do
    if [[ -d "$dir" ]]; then
      log "[DRY RUN]   $(basename "$dir"): EXISTS"
    else
      log "[DRY RUN]   $(basename "$dir"): NOT YET CREATED (first iteration will create)"
    fi
  done

  # Check ports
  for port in $MOCK_BACKEND_PORT $CHAT_INTERFACE_PORT; do
    if check_port "$port"; then
      log "[DRY RUN]   Port $port: IN USE"
    else
      log "[DRY RUN]   Port $port: FREE"
    fi
  done

  exit 0
fi

# ─────────────────────────────────────────────────────────
# Main Loop
# ─────────────────────────────────────────────────────────

PREV_SCORE=0
STALL_COUNT=0
FATAL_PENALTY_COUNT=0

while true; do
  VERSION=$((VERSION + 1))
  TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

  log ""
  log "════════════════════════════════════════"
  log "  Iteration v$VERSION — $TIMESTAMP"
  log "════════════════════════════════════════"

  # --- Max iterations check ---
  if [[ $VERSION -gt $MAX_ITERATIONS ]]; then
    log "Max iterations ($MAX_ITERATIONS) reached. Stopping."
    break
  fi

  # --- Cost check ---
  ESTIMATED_COST=$(echo "$VERSION * $COST_PER_ITERATION" | bc)
  if (( $(echo "$ESTIMATED_COST > $MAX_COST" | bc -l) )); then
    log "Cost cap reached (~\$$ESTIMATED_COST > \$$MAX_COST). Stopping."
    break
  fi

  # --- Create output dirs ---
  mkdir -p "$SCREENSHOTS_DIR/v$VERSION"

  # --- Prepare paths ---
  PREV_VERSION=$((VERSION - 1))
  LAST_EVAL="$EVAL_DIR/v${PREV_VERSION}-eval.md"
  CHANGELOG_PATH="$CHANGELOG_DIR/v${VERSION}-changelog.md"
  EVAL_REPORT="$EVAL_DIR/v${VERSION}-eval.md"

  LAST_EVAL_CONTEXT=""
  if [[ -f "$LAST_EVAL" ]]; then
    LAST_EVAL_CONTEXT="
Read eval-reports/v${PREV_VERSION}-eval.md for specific feedback to address."
  else
    LAST_EVAL_CONTEXT="
This is the FIRST iteration. No previous eval report exists."
  fi

  # ─── Step 1: Generator ───
  log "[v$VERSION] Running Generator agent..."

  GENERATOR_PROMPT=$(cat "$PROMPTS_DIR/generator.md")
  GENERATOR_PROMPT="${GENERATOR_PROMPT}

---

## Iteration Context (injected by orchestrator)

This is iteration ${VERSION}.
${LAST_EVAL_CONTEXT}

Save changelog to: ${CHANGELOG_PATH}

${SOURCE_CONTEXT}

## Key Paths (absolute)
- SPEC.md: ${HARNESS_DIR}/SPEC.md
- EVAL_CRITERIA.md: ${HARNESS_DIR}/EVAL_CRITERIA.md
- progress.md: ${HARNESS_DIR}/progress.md
- Design doc: ${HARNESS_DIR}/reference/Jijian-Context-Layer.md
- Eval reports dir: ${EVAL_DIR}/
- Changelog dir: ${CHANGELOG_DIR}/"

  log "[v$VERSION] Generator started (expected ~10-20min)..."
  echo "$GENERATOR_PROMPT" | claude -p \
    --allowedTools "$GENERATOR_TOOLS" \
    > "$CHANGELOG_DIR/v${VERSION}-generator-output.txt" 2>&1 &
  CLAUDE_PID=$!

  # Heartbeat
  HEARTBEAT=0
  while kill -0 $CLAUDE_PID 2>/dev/null; do
    sleep 30
    HEARTBEAT=$((HEARTBEAT + 1))
    OUT_SIZE=$(wc -c < "$CHANGELOG_DIR/v${VERSION}-generator-output.txt" 2>/dev/null || echo 0)
    CHANGELOG_EXISTS="no"
    [[ -f "$CHANGELOG_PATH" ]] && CHANGELOG_EXISTS="yes ($(wc -c < "$CHANGELOG_PATH") bytes)"
    log "[v$VERSION] Generator heartbeat #${HEARTBEAT} (${HEARTBEAT}x30s) — output=${OUT_SIZE}b changelog=${CHANGELOG_EXISTS}"
  done
  wait $CLAUDE_PID
  CLAUDE_EXIT=$?

  if [[ $CLAUDE_EXIT -ne 0 ]]; then
    err "[v$VERSION] Generator failed (exit=$CLAUDE_EXIT). Retrying once..."
    echo "$GENERATOR_PROMPT" | claude -p \
      --allowedTools "$GENERATOR_TOOLS" \
      > "$CHANGELOG_DIR/v${VERSION}-generator-output-retry.txt" 2>&1
    if [[ $? -ne 0 ]]; then
      err "[v$VERSION] Generator failed on retry. Logging and continuing."
      echo "| v$VERSION | $TIMESTAMP | FAIL | - | - | - | - | - | - | Generator agent failed |" >> "$PROGRESS_FILE"
      continue
    fi
  fi

  log "[v$VERSION] Generator complete."

  if [[ ! -f "$CHANGELOG_PATH" ]]; then
    log "[v$VERSION] WARNING: Generator did not write changelog to $CHANGELOG_PATH"
  fi

  # ─── Step 2: Frozen file check ───
  log "[v$VERSION] Checking frozen files..."
  check_frozen_files || true
  FROZEN_VIOLATIONS=$?
  if [[ $FROZEN_VIOLATIONS -gt 0 ]]; then
    log "[v$VERSION] WARNING: ${FROZEN_VIOLATIONS} frozen file(s) reverted."
  fi

  # ─── Step 3: Architecture violation check ───
  log "[v$VERSION] Checking architecture violations..."
  ARCH_VIOLATIONS=0
  if [[ -d "$CONTEXT_LAYER/src/core" ]]; then
    check_architecture || true
    ARCH_VIOLATIONS=$?
  fi

  # ─── Step 4: TypeScript validation ───
  log "[v$VERSION] Running tsc validation..."
  TSC_PASS=true
  TSC_ERRORS=""

  if [[ -d "$CONTEXT_LAYER" ]] && [[ -f "$CONTEXT_LAYER/tsconfig.json" ]]; then
    if ! (cd "$CONTEXT_LAYER" && npx tsc --noEmit 2>"$EVAL_DIR/v${VERSION}-context-layer-tsc.txt"); then
      TSC_PASS=false
      TSC_ERRORS="context-layer tsc failed"
      err "[v$VERSION] context-layer tsc FAILED"
    fi
  fi

  if [[ -d "$CONTEXT_LAYER_REACT" ]] && [[ -f "$CONTEXT_LAYER_REACT/tsconfig.json" ]]; then
    if ! (cd "$CONTEXT_LAYER_REACT" && npx tsc --noEmit 2>"$EVAL_DIR/v${VERSION}-context-layer-react-tsc.txt"); then
      TSC_PASS=false
      TSC_ERRORS="${TSC_ERRORS}; context-layer-react tsc failed"
      err "[v$VERSION] context-layer-react tsc FAILED"
    fi
  fi

  if [[ -d "$MOCK_SOLUTION" ]] && [[ -f "$MOCK_SOLUTION/tsconfig.json" ]]; then
    if ! (cd "$MOCK_SOLUTION" && npx tsc --noEmit 2>"$EVAL_DIR/v${VERSION}-mock-tsc.txt"); then
      TSC_PASS=false
      TSC_ERRORS="${TSC_ERRORS}; mock-solution tsc failed"
      err "[v$VERSION] mock-solution tsc FAILED"
    fi
  fi

  if ! $TSC_PASS; then
    log "[v$VERSION] tsc validation FAILED — proceeding to eval (evaluator will score accordingly)"
  else
    log "[v$VERSION] tsc validation: PASS"
  fi

  # ─── Step 5: Git snapshot (after generator) ───
  log "[v$VERSION] Creating git snapshot..."
  (cd "$PROJECT_ROOT" && \
    git add \
      packages/context-layer/ \
      packages/context-layer-react/ \
      packages/chat-interface/src/components/chat/MentionPicker.tsx \
      packages/chat-interface/src/components/chat/MentionContext.tsx \
      solutions/mock/context-layer-demo/ \
      harness-workspace/reference-picker-core-module/e2e/ \
      2>/dev/null && \
    git commit -m "feat(frontend): context-layer harness v$VERSION iteration" -q 2>/dev/null) || \
    log "[v$VERSION] WARNING: git commit failed (no changes or git issue)"

  # ─── Step 6: (Re)start dev servers for evaluator ───
  log "[v$VERSION] Managing dev servers for evaluation..."
  stop_servers
  sleep 2

  SERVERS_OK=false
  MOCK_OK=false
  CHAT_OK=false
  if [[ -d "$MOCK_SOLUTION" ]] && [[ -f "$MOCK_SOLUTION/package.json" ]]; then
    if start_mock_solution; then
      MOCK_OK=true
      SERVERS_OK=true  # E2E tests only need mock solution on :3021
      if start_chat_interface; then
        CHAT_OK=true
      else
        log "[v$VERSION] Chat interface failed to start (not needed for E2E tests)"
      fi
    fi
  fi

  SERVER_CONTEXT=""
  if $MOCK_OK; then
    SERVER_CONTEXT="
## 服务状态
- **Mock solution**: http://localhost:${MOCK_BACKEND_PORT} — RUNNING
- **Chat interface**: $($CHAT_OK && echo "http://localhost:${CHAT_INTERFACE_PORT} — RUNNING" || echo "NOT RUNNING (not needed for E2E)")
- E2E tests can be run: cd ${E2E_DIR} && npx playwright test
- Playwright webServer config will auto-start mock solution if needed"
  else
    SERVER_CONTEXT="
## 服务状态
- **WARNING**: Mock solution 未启动。尝试运行: cd ${E2E_DIR} && npx playwright test (webServer 会自动启动)
- 如果 npx playwright test 也失败，D1 max 1/5。"
  fi

  # ─── Step 7: Evaluator ───
  log "[v$VERSION] Running Evaluator agent..."

  EVALUATOR_PROMPT=$(cat "$PROMPTS_DIR/evaluator.md")
  EVALUATOR_PROMPT="${EVALUATOR_PROMPT}

---

## Evaluation Context (injected by orchestrator)

This is evaluation for v${VERSION}.
${SERVER_CONTEXT}

${SOURCE_CONTEXT}

## Key Paths (absolute)
- SPEC.md: ${HARNESS_DIR}/SPEC.md
- EVAL_CRITERIA.md: ${HARNESS_DIR}/EVAL_CRITERIA.md
- Design doc: ${HARNESS_DIR}/reference/Jijian-Context-Layer.md
- progress.md: ${HARNESS_DIR}/progress.md
- Changelog: ${CHANGELOG_PATH}
- Write eval report to: ${EVAL_REPORT}
- Screenshots dir: ${SCREENSHOTS_DIR}/v${VERSION}/"

  log "[v$VERSION] Evaluator started (expected ~10-15min)..."
  echo "$EVALUATOR_PROMPT" | claude -p \
    --allowedTools "$EVALUATOR_TOOLS" \
    > "$EVAL_DIR/v${VERSION}-evaluator-output.txt" 2>&1 &
  CLAUDE_PID=$!

  HEARTBEAT=0
  while kill -0 $CLAUDE_PID 2>/dev/null; do
    sleep 30
    HEARTBEAT=$((HEARTBEAT + 1))
    OUT_SIZE=$(wc -c < "$EVAL_DIR/v${VERSION}-evaluator-output.txt" 2>/dev/null || echo 0)
    EVAL_EXISTS="no"
    [[ -f "$EVAL_REPORT" ]] && EVAL_EXISTS="yes ($(wc -c < "$EVAL_REPORT") bytes)"
    log "[v$VERSION] Evaluator heartbeat #${HEARTBEAT} (${HEARTBEAT}x30s) — output=${OUT_SIZE}b eval=${EVAL_EXISTS}"
  done
  wait $CLAUDE_PID
  CLAUDE_EXIT=$?

  if [[ $CLAUDE_EXIT -ne 0 ]]; then
    err "[v$VERSION] Evaluator failed (exit=$CLAUDE_EXIT)."
    echo "| v$VERSION | $TIMESTAMP | ERR | - | - | - | - | - | - | Evaluator agent failed |" >> "$PROGRESS_FILE"
    continue
  fi

  log "[v$VERSION] Evaluator complete."

  # ─── Step 8: Extract score ───
  if [[ ! -f "$EVAL_REPORT" ]]; then
    err "[v$VERSION] Eval report not found at $EVAL_REPORT"
    echo "| v$VERSION | $TIMESTAMP | ERR | - | - | - | - | - | - | No eval report written |" >> "$PROGRESS_FILE"
    continue
  fi

  SCORE=$(extract_score "$EVAL_REPORT")
  log "[v$VERSION] Score: $SCORE/100 (previous: $PREV_SCORE/100)"

  # Extract per-dimension scores
  D1=$(grep -oE 'D1.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")
  D2=$(grep -oE 'D2.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")
  D3=$(grep -oE 'D3.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")
  D4=$(grep -oE 'D4.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")
  D5=$(grep -oE 'D5.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")
  D6=$(grep -oE 'D6.*Score: ([0-9])/5' "$EVAL_REPORT" | grep -oE '[0-9]/5' | head -1 || echo "-")

  # Extract top issue
  TOP_ISSUE=$(grep -A1 "Priority Fix" "$EVAL_REPORT" 2>/dev/null | tail -1 | cut -c1-80 || echo "See eval report")

  # Changelog summary
  if [[ -f "$CHANGELOG_PATH" ]]; then
    CHANGES=$(grep "^- " "$CHANGELOG_PATH" | head -3 | tr '\n' '; ' | cut -c1-80)
  else
    CHANGES="(no changelog)"
  fi

  # Update progress
  echo "| v$VERSION | $TIMESTAMP | $SCORE | $D1 | $D2 | $D3 | $D4 | $D5 | $D6 | $TOP_ISSUE |" >> "$PROGRESS_FILE"

  # ─── Step 9: Git snapshot (after eval) ───
  (cd "$PROJECT_ROOT" && \
    git add "$HARNESS_DIR/eval-reports/" "$HARNESS_DIR/changelogs/" "$HARNESS_DIR/progress.md" "$HARNESS_DIR/screenshots/" 2>/dev/null && \
    git commit -m "feat(frontend): context-layer harness v$VERSION eval — score ${SCORE}/100" -q 2>/dev/null) || true

  # ─── Step 10: Exit conditions ───

  # Target reached
  if [[ $SCORE -ge $TARGET_SCORE ]]; then
    log ""
    log "TARGET REACHED: $SCORE/100 >= $TARGET_SCORE/100"
    break
  fi

  # Regression detection + auto-revert
  if [[ $PREV_SCORE -gt 0 ]] && [[ $((PREV_SCORE - SCORE)) -ge $ROLLBACK_THRESHOLD ]]; then
    log "[v$VERSION] REGRESSION: $SCORE < $PREV_SCORE by $((PREV_SCORE - SCORE)) points"
    log "[v$VERSION] Reverting source code to previous iteration..."
    (cd "$PROJECT_ROOT" && git checkout HEAD~2 -- \
      packages/context-layer/ \
      packages/context-layer-react/ \
      packages/chat-interface/src/components/chat/MentionPicker.tsx \
      packages/chat-interface/src/components/chat/MentionContext.tsx \
      solutions/mock/context-layer-demo/ \
      harness-workspace/reference-picker-core-module/e2e/ \
      2>/dev/null || true)
    (cd "$PROJECT_ROOT" && git add -A && git commit -m "fix(frontend): context-layer harness v$VERSION reverted — regression" -q 2>/dev/null) || true
    SCORE=$PREV_SCORE
    log "[v$VERSION] Reverted to previous score: $SCORE"
  fi

  # Fatal penalty tracking
  if grep -q "P1\|P2\|P3" "$EVAL_REPORT" 2>/dev/null && grep -q "FAIL\|触发\|VIOLATION" "$EVAL_REPORT" 2>/dev/null; then
    FATAL_PENALTY_COUNT=$((FATAL_PENALTY_COUNT + 1))
    if [[ $FATAL_PENALTY_COUNT -ge $FATAL_PENALTY_MAX_CONSECUTIVE ]]; then
      log ""
      log "FATAL: Consecutive fatal penalties for $FATAL_PENALTY_COUNT rounds. Human intervention needed."
      break
    fi
  else
    FATAL_PENALTY_COUNT=0
  fi

  # Diminishing returns
  if [[ $PREV_SCORE -gt 0 ]]; then
    IMPROVEMENT=$((SCORE - PREV_SCORE))
    if [[ $IMPROVEMENT -lt $DIMINISHING_THRESHOLD ]]; then
      STALL_COUNT=$((STALL_COUNT + 1))
    else
      STALL_COUNT=0
    fi

    if [[ $STALL_COUNT -ge $DIMINISHING_MAX_STALLS ]]; then
      log ""
      log "DIMINISHING RETURNS: Score improved < $DIMINISHING_THRESHOLD for $STALL_COUNT consecutive rounds."
      log "Final score: $SCORE/100. Stopping."
      break
    fi
  fi

  PREV_SCORE=$SCORE

  # Stop servers between iterations (Generator will modify code)
  stop_servers
done

# ─── Cleanup ───
stop_servers

log ""
log "═══════════════════════════════════════════"
log "  Harness complete. Final score: ${PREV_SCORE}/100"
log "  Progress: $PROGRESS_FILE"
log "  History: git log --grep='context-layer harness' --oneline"
log "═══════════════════════════════════════════"
